### ISSUE TITLE
Functions is not a valid Features value.

### ISSUE THREAD

**Issue by kushagrabansal** [trailheadapps/functions-recipes#237]
### Summary

Unable to create a scratch org with Functions as a feature.

### Salesforce Org Type

Developer Edition Org

### Function Language

JavaScript

### Steps To Reproduce

1. Authorise a sfdx project with a dev org
2. Add one of the features in the config file as Functions 
3. run this command to create scratch org : sfdx force:org:create -s -f config/project-scratch-def.json -a fn-org

### Current Behavior

The CLI throws an error saying : ERROR running force:org:create:  Functions is not a valid Features value.

### Expected Behavior

The CLI should create a scratch org

### Relevant Log Output

```shell
ERROR running force:org:create:  Functions is not a valid Features value.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianduque** [comment]
@kushagrabansal Hello!

A Developer Edition Org doesn't support Functions, you'll need a Functions License to create a scratch org. 

You can apply for a Trial by signing up using the following form: https://functions.salesforce.com/signups or requesting a courtesy license to your AE.

Or, you can use this repository using the [Local Development experience](https://github.com/trailheadapps/functions-recipes#local-development).
