### ISSUE TITLE
Old API version returned in OrgInfo function

### ISSUE THREAD

**Issue by pozil** [trailheadapps/functions-recipes#324]
### Summary

When execution the `OrgInfo` recipe, the function returns API version 53.0 whereas the org is on Spring '22 (API v54.0).

![Screen Shot 2022-02-16 at 14 47 15](https://user-images.githubusercontent.com/5071767/154278192-48587101-f0e1-4122-b214-72636c4de8b9.png)

### Salesforce Org Type

Scratch Org

### Function Language

TypeScript

### Steps To Reproduce

Run the `OrgInfo` function with the Run Function button.

### Current Behavior

"apiVersion": "53.0"

### Expected Behavior

"apiVersion": "54.0"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianduque** [comment]
This is addressed in #476 with a note
