### ISSUE TITLE
Incorrect Java class name

### ISSUE THREAD

**Issue by NVandenBossche** [trailheadapps/functions-recipes#354]
The Java class name for JsonResponse.java in the Process Large Data Volumes recipe is incorrect in the UI (see screenshot).
![image](https://user-images.githubusercontent.com/13299887/156170991-6439c581-a733-4a03-b63d-64343b98fcdd.png)

These are the files referencing "JavaResponse.java" instead of "JsonReponse.java".
![image](https://user-images.githubusercontent.com/13299887/156171292-69c6233d-26a9-4768-9608-1e972e4a960e.png)

**Comment by julianduque** [comment]
@NVandenBossche Hey, great catch! Thanks for reporting.

**Comment by julianduque** [comment]
Thanks @NVandenBossche, a fix has been pushed to the `main` branch!
