### ISSUE TITLE
Winter '23: invalid value 'twoColumn' for attribute flowLayout

### ISSUE THREAD

**Issue by mars** [trailheadapps/functions-recipes#529]
### Summary

When deploying the Salesforce metadata to a Winter '23 org, the following error is returned:

```
        === Component Failures [1]
        
         Type  Name       Problem                                                                                                      
         ───── ────────── ──────────────────────────────────────────────────────────────────────────────────────────────────────────── 
         Error Invocation Component [flowruntime:interview] attribute [flowLayout]: invalid value 'twoColumn' for attribute flowLayout 
        
        ERROR running force:source:push:  Push failed.
```

It seems this is a breaking change, even though the [release notes](https://help.salesforce.com/s/articleView?id=release-notes.rn_automate_flow_runtime_two_column_layouts.htm&type=5&release=236) say,

> Starting in Winter ’23, two-column layouts are ignored.

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

Deploy this project to a Salesforce org already upgraded to Winter '23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mars** [comment]
I was able to get past this error by deleting the `<componentInstanceProperties>` element containing the offending value:
https://github.com/trailheadapps/functions-recipes/blob/main/force-app/main/default/flexipages/Invocation.flexipage-meta.xml#L12-L15

Not sure how this breaks the intended visual layout, but at least deployment works again.

**Comment by julianduque** [comment]
Thanks @mars, we are working on this fix now and the repo will be updated for Winter '23

**Comment by julianduque** [comment]
Fixed in `main` thanks @mars !
