### ISSUE TITLE
01_Intro_ProcessLargeData_Java does not calculate distance correctly

### ISSUE THREAD

**Issue by msducheminjr** [trailheadapps/functions-recipes#707]
### Summary

The calculate distance functions between the Java and JS versions of `01_Intro_ProcessLargeData` do not calculate similar distances. The Java version is missing the `dist = dist * 60 * 1.1515;` statement that exists in the JS version of the distance function.

```java
// java
distance(36.169090, -115.140579, 36.1657, -115.141);
// => 0.003406994620636472
```
```javascript
// js
distance(36.169090, -115.140579, 36.1657, -115.141);
// => 0.23538925833977384
```

The JS implementation with the `dist = dist * 60 * 1.1515;` is more accurate than the Java implementation. Will open a PR to correct the Java version and add an assertion about the distance in tests for both Java and JavaScript.

### Salesforce Org Type

Developer Edition Org

### Function Language

Java

### Steps To Reproduce

Call distance with any set of coordinates in the Java version. Compare the distance to the coordinates in Google Maps.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianduque** [comment]
@msducheminjr good catch!! Thank you very much for reporting and submitting a PR, I'll review and merge
